name: Renovate - called workflow

on:
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string

concurrency: renovate

jobs:
  Run-Renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Renovate JSON
        run: jq type default.json

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.0
        with:
          configurationFile: .github/renovate.json
          renovate-version: 36.107.1
          token: ${{ steps.generate_token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
